### PR TITLE
Add logging test to all test

### PR DESCRIPTION
**Pull request by kairbon**

### CODE REVIEW

**Comment by BryainZhang** [comment]
The last test script is not in the current directory, change it to ../run_logging_check_test.sh

**Comment by kairbon** [comment]
> The last test script is not in the current directory, change it to ../run_logging_check_test.sh

OK, done.

**Review by BryainZhang — APPROVED** [review]

**Comment by kairbon** [comment]
image
@BryainZhang 
Is that all right? I also find this in previous PR.

**Comment by BryainZhang** [comment]
> image
> @BryainZhang
> Is that all right? I also find this in previous PR.

Yes, this is correct, See pr #150，RAFTCPP_CHECK(false) need to be interrupted.

**Comment by BryainZhang** [comment]
> @BryainZhang
> Is that all right? I also find this in previous PR.

@kairbon 
Yes, this is correct, see PR #150，RAFTCPP_CHECK(false) need to be interrupted.

**Pull request merged**
